# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "(.idea|node_modules|.tox)"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: fix-encoding-pragma
        args:
          - --remove
  - repo: https://github.com/timothycrosley/isort
    rev: "5.9.3"
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-broken-line
          - flake8-bugbear
          - flake8-builtins
          - flake8-coding
          - flake8-commas
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-quotes
          - flake8-tidy-imports
          - pep8-naming
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args:
          - "-cpyproject.toml"
          - "--quiet"
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade
        args:
          - --py3-plus
  - repo: local
    hooks:
      - id: towncrier
        name: towncrier
        entry: inv towncrier-check
        language: system
        pass_filenames: false
        always_run: true
