name: Event Logger
on: push

jobs:
  log-github-event-goodies:
    name: "LOG Everything on GitHub Event"
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        env:
          EVENT_JSON: ${{ toJSON(github.event) }}
        run: |
          printf '%s\n' "$EVENT_JSON"
